apiVersion: v1
kind: Service
metadata:
  name: flask-anchal
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "flask-anchal-service-80-neg"}}}'
  labels:
    app: flask-anchal
    tier: web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: flask-anchal
    tier: web
